// Builds migrations/0005_geo.sql from GeoNames (https://www.geonames.org, CC-BY 4.0):
//   data/geonames/countryInfo.txt, admin1CodesASCII.txt, cities15000.txt (cities with 15,000+ people).
// Run: npx tsx scripts/build-geo.ts

import { readFileSync, writeFileSync } from "node:fs";

const DIR = "data/geonames";
const rows = (file: string) =>
  readFileSync(`${DIR}/${file}`, "utf8")
    .split(/\r?\n/)
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => l.split("\t"));

const q = (v: string | number | null) =>
  v == null || v === "" ? "NULL" : typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`;

const cities = rows("cities15000.txt").map((c) => ({
  id: Number(c[0]),
  name: c[1],
  ascii: c[2],
  lat: Number(c[4]),
  lng: Number(c[5]),
  country: c[8],
  region: c[10] || null,
  population: Number(c[14]) || 0,
}));
const countriesWithCities = new Set(cities.map((c) => c.country));

const countries = rows("countryInfo.txt")
  .map((c) => ({ code: c[0], name: c[4], continent: c[8] }))
  .filter((c) => countriesWithCities.has(c.code));

const usedRegions = new Set(cities.map((c) => `${c.country}.${c.region}`));
const regions = rows("admin1CodesASCII.txt")
  .map((r) => {
    const [country, code] = r[0].split(".");
    return { country, code, name: r[1] };
  })
  .filter((r) => usedRegions.has(`${r.country}.${r.code}`));

const out: string[] = [
  "-- Generated by scripts/build-geo.ts from GeoNames (geonames.org, CC-BY 4.0). Do not edit by hand.",
  "CREATE TABLE geo_countries (code TEXT PRIMARY KEY, name TEXT NOT NULL, continent TEXT);",
  "CREATE TABLE geo_regions (country TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, PRIMARY KEY (country, code));",
  `CREATE TABLE geo_cities (id INTEGER PRIMARY KEY, name TEXT NOT NULL, ascii TEXT NOT NULL, country TEXT NOT NULL,
  region TEXT, population INTEGER NOT NULL DEFAULT 0, lat REAL NOT NULL, lng REAL NOT NULL);`,
  "CREATE INDEX idx_geo_cities_region ON geo_cities(country, region, population DESC);",
  "CREATE INDEX idx_geo_cities_ascii ON geo_cities(ascii COLLATE NOCASE);",
];
const chunked = <T>(items: T[], size: number, fn: (chunk: T[]) => string) => {
  for (let i = 0; i < items.length; i += size) out.push(fn(items.slice(i, i + size)));
};
chunked(countries, 300, (ch) => `INSERT INTO geo_countries VALUES ${ch.map((c) => `(${q(c.code)},${q(c.name)},${q(c.continent)})`).join(",")};`);
chunked(regions, 500, (ch) => `INSERT INTO geo_regions VALUES ${ch.map((r) => `(${q(r.country)},${q(r.code)},${q(r.name)})`).join(",")};`);
chunked(
  cities,
  400,
  (ch) =>
    `INSERT INTO geo_cities VALUES ${ch
      .map((c) => `(${c.id},${q(c.name)},${q(c.ascii)},${q(c.country)},${q(c.region)},${c.population},${c.lat},${c.lng})`)
      .join(",")};`,
);

writeFileSync("migrations/0005_geo.sql", out.join("\n") + "\n", "utf8");
console.log(`countries ${countries.length}, regions ${regions.length}, cities ${cities.length}`);
