// Google Business Profile categories grouped by industry, for the category picker and
// the search box. Names are Google's exact category strings. Generated from research
// (sources: https://github.com/lobstrio/google-business-categories (primary source of truth: 4,053 GCID-deduped GBP categories, last updated Sept 2026; raw files used: data/google-business-categories.by-bucket.json, data/google-business-categories.txt, data/gcid-map.json, data/google-business-categories.full.json), https://www.lobstr.io/blog/google-business-categories, https://pleper.com/index.php?do=tools&sdo=gmb_categories (PlePer GBP categories tool; list is generated per language/country, default en/US), https://daltonluka.com/blog/google-my-business-categories (4,046 categories, May 9 2026; used for cross-checking exact names)), checked against a published GBP list.

export interface Industry {
  industry: string;
  categories: string[];
}

export const INDUSTRIES: Industry[] = [
  {
    "industry": "Medical & Healthcare",
    "categories": [
      "Doctor",
      "Medical clinic",
      "Medical Center",
      "Medical office",
      "Hospital",
      "Family practice physician",
      "General practitioner",
      "Internist",
      "Urgent care center",
      "Walk-in clinic",
      "Pediatrician",
      "Pediatric clinic",
      "Obstetrician-gynecologist",
      "Women's health clinic",
      "Dermatologist",
      "Chiropractor",
      "Physical therapist",
      "Physical therapy clinic",
      "Physical rehabilitation center",
      "Rehabilitation center",
      "Optometrist",
      "Ophthalmologist",
      "Eye care center",
      "Podiatrist",
      "Cardiologist",
      "Orthopedic surgeon",
      "Orthopedic clinic",
      "Urologist",
      "Gastroenterologist",
      "Endocrinologist",
      "Allergist",
      "Neurologist",
      "Otolaryngologist",
      "Oncologist",
      "Pain management physician",
      "Sports medicine clinic",
      "Sleep clinic",
      "Fertility clinic",
      "Plastic surgeon",
      "Psychiatrist",
      "Psychologist",
      "Psychotherapist",
      "Counselor",
      "Marriage or relationship counselor",
      "Mental health clinic",
      "Mental health service",
      "Addiction treatment center"
    ]
  },
  {
    "industry": "Dental",
    "categories": [
      "Dentist",
      "Dental clinic",
      "Cosmetic dentist",
      "Pediatric dentist",
      "Emergency dental service",
      "Orthodontist",
      "Endodontist",
      "Periodontist",
      "Prosthodontist",
      "Oral surgeon",
      "Oral and maxillofacial surgeon",
      "Dental implants provider",
      "Dental implants periodontist",
      "Dental hygienist",
      "Denture care center",
      "Dental laboratory",
      "Teeth whitening service",
      "Dental radiology",
      "Dental supply store",
      "Dental school"
    ]
  },
  {
    "industry": "Home Services",
    "categories": [
      "Plumber",
      "Drainage service",
      "HVAC contractor",
      "Heating contractor",
      "Furnace repair service",
      "Air conditioning contractor",
      "Air conditioning repair service",
      "Electrician",
      "Electrical installation service",
      "Roofing contractor",
      "Gutter service",
      "Gutter cleaning service",
      "Siding contractor",
      "Window installation service",
      "Garage door supplier",
      "Locksmith",
      "Landscaper",
      "Landscape designer",
      "Lawn care service",
      "Tree service",
      "Lawn sprinkler system contractor",
      "Snow removal service",
      "Pest control service",
      "House cleaning service",
      "Janitorial service",
      "Carpet cleaning service",
      "Window cleaning service",
      "Pressure washing service",
      "Air duct cleaning service",
      "Dry cleaner",
      "Laundromat",
      "Appliance repair service",
      "Handyman/Handywoman/Handyperson",
      "Painter",
      "Junk removal service",
      "Dumpster rental service",
      "Moving service",
      "Moving and storage service",
      "Water damage restoration service",
      "Fire damage restoration service",
      "Water purification company",
      "Septic system service",
      "Chimney sweep",
      "Security system installation service",
      "Pool cleaning service"
    ]
  },
  {
    "industry": "Construction & Contractors",
    "categories": [
      "General contractor",
      "Contractor",
      "Construction company",
      "Remodeler",
      "Kitchen remodeler",
      "Bathroom remodeler",
      "Interior construction contractor",
      "Home builder",
      "Custom home builder",
      "Concrete contractor",
      "Masonry contractor",
      "Paving contractor",
      "Asphalt contractor",
      "Excavating contractor",
      "Demolition contractor",
      "Crane service",
      "Fence contractor",
      "Deck builder",
      "Flooring contractor",
      "Tile contractor",
      "Carpet installer",
      "Wood floor installation service",
      "Dry wall contractor",
      "Plasterer",
      "Stucco contractor",
      "Insulation contractor",
      "Carpenter",
      "Cabinet maker",
      "Countertop contractor",
      "Glazier",
      "Skylight contractor",
      "Sunroom contractor",
      "Garage builder",
      "Swimming pool contractor",
      "Waterproofing service",
      "Roofing supply store",
      "Solar energy company",
      "Solar energy system service",
      "Architect",
      "Structural engineer",
      "Civil engineer",
      "Engineering consultant",
      "Land surveyor",
      "Building inspector",
      "Landscape architect"
    ]
  },
  {
    "industry": "Automotive",
    "categories": [
      "Auto repair shop",
      "Car repair and maintenance service",
      "Mechanic",
      "Auto body shop",
      "Car dealer",
      "Used car dealer",
      "Motor vehicle dealer",
      "Truck dealer",
      "Auto broker",
      "Car leasing service",
      "Tire shop",
      "Tire repair shop",
      "Car wash",
      "Self service car wash",
      "Car detailing service",
      "Auto glass shop",
      "Auto glass repair service",
      "Transmission shop",
      "Brake shop",
      "Muffler shop",
      "Oil change service",
      "Auto tune up service",
      "Wheel alignment service",
      "Auto radiator repair service",
      "Towing service",
      "Auto wrecker",
      "Auto electrical service",
      "Auto air conditioning service",
      "Auto painting",
      "Auto dent removal service",
      "Auto window tinting service",
      "Vehicle wrapping service",
      "Car stereo store",
      "Auto parts store",
      "Used auto parts store",
      "Motorcycle dealer",
      "Motorcycle repair shop",
      "RV dealer",
      "RV repair shop",
      "Boat dealer",
      "Boat repair shop",
      "Truck repair shop",
      "Diesel engine repair service",
      "Smog inspection station",
      "Car inspection station"
    ]
  },
  {
    "industry": "Legal",
    "categories": [
      "Lawyer",
      "Law firm",
      "Legal services",
      "Barrister",
      "Personal injury attorney",
      "Criminal justice attorney",
      "Family law attorney",
      "Divorce lawyer",
      "Immigration attorney",
      "Immigration & naturalization service",
      "Bankruptcy attorney",
      "Estate planning attorney",
      "Probate attorney",
      "Elder law attorney",
      "Real estate attorney",
      "Business attorney",
      "Employment attorney",
      "Labor relations attorney",
      "Social security attorney",
      "Tax attorney",
      "Patent attorney",
      "Trial attorney",
      "General practice attorney",
      "Civil law attorney",
      "Estate litigation attorney",
      "Insurance attorney",
      "Environmental attorney",
      "Administrative attorney",
      "Medical lawyer",
      "Bail bonds service",
      "Notary public",
      "Process server",
      "Paralegal services provider",
      "Mediation service",
      "Attorney referral service"
    ]
  },
  {
    "industry": "Financial & Insurance",
    "categories": [
      "Insurance agency",
      "Insurance broker",
      "Insurance agent",
      "Insurance company",
      "Auto insurance agency",
      "Home insurance agency",
      "Life insurance agency",
      "Health insurance agency",
      "Dental insurance agency",
      "Renter's insurance agency",
      "Motorcycle insurance agency",
      "Income protection insurance agency",
      "Financial advisor",
      "Financial planner",
      "Financial consultant",
      "Investment service",
      "Investment company",
      "Investment bank",
      "Mortgage broker",
      "Mortgage lender",
      "Loan agency",
      "Bank",
      "Savings bank",
      "Financial institution",
      "Business banking service",
      "Credit union",
      "Federal credit union",
      "Car finance and loan company",
      "Credit counseling service",
      "Debt collection agency",
      "Check cashing service",
      "Stock broker",
      "Business broker",
      "Finance broker",
      "Escrow service",
      "Bankruptcy service",
      "Money transfer service"
    ]
  },
  {
    "industry": "Real Estate",
    "categories": [
      "Real estate agency",
      "Real estate agent",
      "Real estate consultant",
      "Commercial real estate agency",
      "Industrial real estate agency",
      "Real estate appraiser",
      "Appraiser",
      "Estate appraiser",
      "Real estate surveyor",
      "Property management company",
      "Property maintenance",
      "Apartment rental agency",
      "Real estate rental agency",
      "Condominium rental agency",
      "Short term apartment rental agency",
      "Vacation home rental agency",
      "Holiday home",
      "Apartment complex",
      "Condominium complex",
      "Townhouse complex",
      "Housing association",
      "Real estate developer",
      "Home inspector",
      "Commercial real estate inspector",
      "Title company",
      "Real estate auctioneer",
      "Home staging service",
      "Foreclosure service",
      "Property investment company",
      "Timeshare agency",
      "Office space rental agency",
      "Retail space rental agency",
      "Mobile home park",
      "Housing development",
      "Self-storage facility"
    ]
  },
  {
    "industry": "Beauty & Personal Care",
    "categories": [
      "Hair salon",
      "Beauty salon",
      "Hairdresser",
      "Barber shop",
      "Nail salon",
      "Day spa",
      "Spa",
      "Medical spa",
      "Massage spa",
      "Facial spa",
      "Eyelash salon",
      "Eyebrow bar",
      "Tanning salon",
      "Waxing hair removal service",
      "Laser hair removal service",
      "Hair removal service",
      "Electrolysis hair removal service",
      "Hair extension technician",
      "Hair extensions supplier",
      "Hair replacement service",
      "Loctician service",
      "Stylist",
      "Beautician",
      "Esthetics service",
      "Skin care clinic",
      "Permanent make-up clinic",
      "Make-up artist",
      "Tattoo shop",
      "Tattoo artist",
      "Tattoo and piercing shop",
      "Tattoo removal service",
      "Body piercing shop",
      "Wig shop",
      "Beauty supply store",
      "Beauty product supplier",
      "Cosmetics store",
      "Perfume store"
    ]
  },
  {
    "industry": "Fitness & Wellness",
    "categories": [
      "Gym",
      "Fitness center",
      "Personal trainer",
      "Women's personal trainer",
      "Physical fitness program",
      "Yoga studio",
      "Bikram yoga studio",
      "Yoga instructor",
      "Pilates studio",
      "Indoor cycling",
      "Martial arts school",
      "Martial arts club",
      "Boxing gym",
      "Boxing club",
      "Kickboxing school",
      "Karate school",
      "Taekwondo school",
      "Jujitsu school",
      "Judo school",
      "Muay Thai boxing gym",
      "Self defense school",
      "Rock climbing gym",
      "Gymnastics center",
      "Swimming instructor",
      "Public swimming pool",
      "Athletic club",
      "Sports club",
      "Sports complex",
      "Wellness center",
      "Wellness program",
      "Health consultant",
      "Massage therapist",
      "Sports massage therapist",
      "Acupuncturist",
      "Acupuncture clinic",
      "Dietitian",
      "Nutritionist",
      "Weight loss service",
      "Meditation center",
      "Health spa",
      "Naturopathic practitioner",
      "Golf instructor",
      "Tennis instructor",
      "Sauna"
    ]
  },
  {
    "industry": "Restaurants & Food",
    "categories": [
      "Restaurant",
      "American restaurant",
      "Pizza restaurant",
      "Italian restaurant",
      "Mexican restaurant",
      "Chinese restaurant",
      "Japanese restaurant",
      "Sushi restaurant",
      "Thai restaurant",
      "Indian restaurant",
      "Vietnamese restaurant",
      "Korean restaurant",
      "Mediterranean restaurant",
      "Greek restaurant",
      "Seafood restaurant",
      "Steak house",
      "Barbecue restaurant",
      "Vegan restaurant",
      "Fast food restaurant",
      "Hamburger restaurant",
      "Chicken restaurant",
      "Chicken wings restaurant",
      "Taco restaurant",
      "Sandwich shop",
      "Deli",
      "Breakfast restaurant",
      "Diner",
      "Family restaurant",
      "Fine dining restaurant",
      "Cafe",
      "Coffee shop",
      "Bakery",
      "Donut shop",
      "Dessert shop",
      "Ice cream shop",
      "Juice shop",
      "Bar",
      "Sports bar",
      "Cocktail bar",
      "Wine bar",
      "Night club",
      "Pub",
      "Bar & grill",
      "Brewery",
      "Winery"
    ]
  },
  {
    "industry": "Retail",
    "categories": [
      "Furniture store",
      "Mattress store",
      "Appliance store",
      "Jewelry store",
      "Jeweler",
      "Clothing store",
      "Boutique",
      "Women's clothing store",
      "Men's clothing store",
      "Shoe store",
      "Bridal shop",
      "Bicycle store",
      "Sporting goods store",
      "Gift shop",
      "Florist",
      "Pharmacy",
      "Liquor store",
      "Wine store",
      "Grocery store",
      "Supermarket",
      "Convenience store",
      "Department store",
      "Gas station",
      "Hardware store",
      "Home improvement store",
      "Lighting store",
      "Pawn shop",
      "Thrift store",
      "Cannabis store",
      "Vaporizer store",
      "Tobacco shop",
      "Toy store",
      "Book store",
      "Antique store",
      "Garden center",
      "Vitamin & supplements store",
      "Health food store",
      "Tile store",
      "Flooring store",
      "Paint store",
      "Optician",
      "Hot tub store",
      "Swimming pool supply store"
    ]
  },
  {
    "industry": "Professional Services",
    "categories": [
      "Marketing agency",
      "Advertising agency",
      "Internet marketing service",
      "Marketing consultant",
      "Media consultant",
      "Branding agency",
      "Design agency",
      "Public relations firm",
      "Graphic designer",
      "Copywriting service",
      "Video production service",
      "Accountant",
      "Accounting firm",
      "Certified public accountant",
      "Bookkeeping service",
      "Tax preparation service",
      "Tax consultant",
      "Payroll service",
      "Auditor",
      "Consultant",
      "Business management consultant",
      "Business to business service",
      "Employment agency",
      "Temp agency",
      "Recruiter",
      "Executive search firm",
      "Human resource consulting",
      "Translation service",
      "Print shop",
      "Commercial printer",
      "Screen printing shop",
      "Sign shop",
      "Promotional products supplier",
      "Office supply store",
      "Shredding service",
      "Call center",
      "Telephone answering service",
      "Coworking space",
      "Virtual office rental",
      "Security guard service",
      "Private investigator",
      "Interior designer",
      "Courier service",
      "Logistics service",
      "Trucking company"
    ]
  },
  {
    "industry": "Education & Childcare",
    "categories": [
      "Preschool",
      "Day care center",
      "Child care agency",
      "Kindergarten",
      "Montessori school",
      "Montessori preschool",
      "Nursery school",
      "After school program",
      "Babysitter",
      "Summer camp organizer",
      "Children's camp",
      "Elementary school",
      "Middle school",
      "High school",
      "Charter school",
      "Private educational institution",
      "Special education school",
      "Adult education school",
      "Tutoring service",
      "Private tutor",
      "Learning center",
      "Test preparation center",
      "Language school",
      "Driving school",
      "Truck driving school",
      "Flight school",
      "Music school",
      "Music instructor",
      "Piano instructor",
      "Guitar instructor",
      "Art school",
      "Dance school",
      "Ballet school",
      "Drama school",
      "Swimming school",
      "Cooking class",
      "Culinary school",
      "Beauty school",
      "Barber school",
      "Real estate school",
      "Nursing school",
      "Trade school",
      "Vocational school",
      "Technical school",
      "Community college",
      "College",
      "University",
      "Computer training school"
    ]
  },
  {
    "industry": "Pets & Veterinary",
    "categories": [
      "Veterinarian",
      "Animal hospital",
      "Emergency veterinarian service",
      "Veterinary pharmacy",
      "Pet groomer",
      "Pet store",
      "Pet supply store",
      "Pet boarding service",
      "Kennel",
      "Cattery",
      "Cat boarding service",
      "Dog day care center",
      "Pet sitter",
      "Dog walker",
      "Pet trainer",
      "Dog trainer",
      "Dog breeder",
      "Cat breeder",
      "Animal shelter",
      "Animal rescue service",
      "Animal control service",
      "Pet adoption service",
      "Pet funeral service",
      "Pet cemetery",
      "Aquarium shop",
      "Bird shop",
      "Reptile store",
      "Animal feed store",
      "Horse boarding stable",
      "Horse trainer",
      "Farrier service",
      "Horse riding school",
      "Pet moving service",
      "Dog park",
      "Dog cafe"
    ]
  },
  {
    "industry": "Events & Photography",
    "categories": [
      "Photographer",
      "Wedding photographer",
      "Commercial photographer",
      "Aerial photographer",
      "Photography studio",
      "Photography service",
      "Photo booth",
      "Photo lab",
      "Video editing service",
      "Event planner",
      "Wedding planner",
      "Party planner",
      "Event management company",
      "Meeting planning service",
      "Exhibition planner",
      "Event venue",
      "Wedding venue",
      "Banquet hall",
      "Wedding chapel",
      "Conference center",
      "Convention center",
      "Live music venue",
      "Karaoke bar",
      "Caterer",
      "Mobile caterer",
      "DJ service",
      "Party equipment rental service",
      "Party store",
      "Tent rental service",
      "Catering equipment rental service",
      "Audiovisual equipment rental service",
      "Event technology service",
      "Wedding service",
      "Wedding store",
      "Wedding dress rental service",
      "Wedding bakery",
      "Children's party service",
      "Entertainer",
      "Entertainment agency",
      "Balloon artist",
      "Magician",
      "Musician",
      "Band",
      "Marriage celebrant"
    ]
  },
  {
    "industry": "Travel & Hospitality",
    "categories": [
      "Hotel",
      "Motel",
      "Inn",
      "Bed & breakfast",
      "Resort hotel",
      "Extended stay hotel",
      "Hostel",
      "Lodging",
      "Guest house",
      "Serviced accommodation",
      "Holiday apartment rental",
      "Cottage rental",
      "Cabin rental agency",
      "Villa",
      "Campground",
      "RV park",
      "Travel agency",
      "Tour agency",
      "Tour operator",
      "Sightseeing tour agency",
      "Boat tour agency",
      "Boat rental service",
      "Bicycle rental service",
      "Cruise agency",
      "Helicopter tour agency",
      "Airport shuttle service",
      "Limousine service",
      "Chauffeur service",
      "Taxi service",
      "Transportation service",
      "Car rental agency",
      "Bus charter",
      "Bus company",
      "Tourist attraction",
      "Tourist information center",
      "Retreat center",
      "Health resort",
      "Wellness hotel",
      "Ski resort",
      "Water park",
      "Theme park",
      "Amusement park"
    ]
  },
  {
    "industry": "Technology & Repair",
    "categories": [
      "Computer repair service",
      "Computer support and services",
      "Computer service",
      "Computer consultant",
      "Computer networking service",
      "Computer security service",
      "Computer store",
      "Used computer store",
      "Computer accessories store",
      "Computer software store",
      "Phone repair service",
      "Mobile phone repair shop",
      "Cell phone store",
      "Cell phone accessory store",
      "Electronics repair shop",
      "Electronics store",
      "Electronics company",
      "Camera store",
      "Home theater store",
      "Small appliance repair service",
      "Data recovery service",
      "Software company",
      "Website designer",
      "Web hosting company",
      "Internet service provider",
      "Cable company",
      "Home automation company",
      "Security system supplier",
      "Television repair service",
      "Printer repair service",
      "Copier repair service",
      "Office equipment repair service",
      "Audio visual equipment repair service",
      "Telecommunications service provider",
      "Telecommunications contractor",
      "Video game store",
      "Drone service"
    ]
  },
  {
    "industry": "Senior Care, Home Health & Funeral",
    "categories": [
      "Assisted living facility",
      "Nursing home",
      "Retirement home",
      "Retirement community",
      "Group home",
      "Home health care service",
      "Home care service",
      "Hospice",
      "Nursing agency",
      "Adult day care center",
      "Senior citizen center",
      "Disability services and support organization",
      "Occupational therapist",
      "Speech pathologist",
      "Audiologist",
      "Hearing aid store",
      "Medical supply store",
      "Mobility equipment supplier",
      "Wheelchair store",
      "Orthotics & prosthetics service",
      "Funeral home",
      "Funeral director",
      "Mortuary",
      "Cremation service",
      "Casket service",
      "Funeral celebrant service",
      "Cemetery",
      "Memorial park",
      "Monument maker"
    ]
  }
];

/** The 100 categories most worth targeting for local-service lead generation. */
export const TOP_100: string[] = [
  "Plumber",
  "HVAC contractor",
  "Air conditioning contractor",
  "Air conditioning repair service",
  "Electrician",
  "Roofing contractor",
  "Window installation service",
  "Garage door supplier",
  "Locksmith",
  "Landscaper",
  "Lawn care service",
  "Tree service",
  "Pest control service",
  "House cleaning service",
  "Janitorial service",
  "Carpet cleaning service",
  "Pressure washing service",
  "Appliance repair service",
  "Handyman/Handywoman/Handyperson",
  "Painter",
  "Junk removal service",
  "Moving service",
  "Water damage restoration service",
  "General contractor",
  "Remodeler",
  "Kitchen remodeler",
  "Bathroom remodeler",
  "Home builder",
  "Concrete contractor",
  "Fence contractor",
  "Flooring contractor",
  "Swimming pool contractor",
  "Solar energy company",
  "Dentist",
  "Dental clinic",
  "Cosmetic dentist",
  "Orthodontist",
  "Chiropractor",
  "Physical therapist",
  "Optometrist",
  "Dermatologist",
  "Medical clinic",
  "Urgent care center",
  "Pediatrician",
  "Obstetrician-gynecologist",
  "Plastic surgeon",
  "Psychologist",
  "Law firm",
  "Personal injury attorney",
  "Criminal justice attorney",
  "Family law attorney",
  "Divorce lawyer",
  "Immigration attorney",
  "Estate planning attorney",
  "Auto repair shop",
  "Auto body shop",
  "Used car dealer",
  "Tire shop",
  "Car detailing service",
  "Auto glass shop",
  "Towing service",
  "Insurance agency",
  "Financial planner",
  "Mortgage broker",
  "Mortgage lender",
  "Real estate agency",
  "Real estate agent",
  "Property management company",
  "Home inspector",
  "Hair salon",
  "Beauty salon",
  "Barber shop",
  "Nail salon",
  "Day spa",
  "Medical spa",
  "Eyelash salon",
  "Gym",
  "Personal trainer",
  "Yoga studio",
  "Martial arts school",
  "Massage therapist",
  "Restaurant",
  "Pizza restaurant",
  "Coffee shop",
  "Furniture store",
  "Jewelry store",
  "Marketing agency",
  "Accountant",
  "Tax preparation service",
  "Bookkeeping service",
  "Preschool",
  "Day care center",
  "Veterinarian",
  "Pet groomer",
  "Dog trainer",
  "Photographer",
  "Event planner",
  "Computer repair service",
  "Assisted living facility",
  "Funeral home"
];

const BY_CATEGORY = new Map(INDUSTRIES.flatMap((i) => i.categories.map((c) => [c.toLowerCase(), i.industry] as const)));

/** Industry a category belongs to, or null if it is not in the list. */
export function industryOf(category: string | null | undefined): string | null {
  return category ? (BY_CATEGORY.get(category.toLowerCase()) ?? null) : null;
}

/** All categories of the named industries. */
export function categoriesOf(industries: string[]): string[] {
  const wanted = new Set(industries.map((i) => i.toLowerCase()));
  return INDUSTRIES.filter((i) => wanted.has(i.industry.toLowerCase())).flatMap((i) => i.categories);
}
